apiVersion: v1
kind: Secret
metadata:
  name: python-secret
  namespace: argocd
type: Opaque
data:
  privateKey: 
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNESlhBQTJBbU9CWXJOK3BxVVpDeWNvbndJckRYb2oxcFMwMzhvbWVzVDR4UUFBQUpBcWs5NCtLcFBlClBnQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDREpYQUEyQW1PQllyTitwcVVaQ3ljb253SXJEWG9qMXBTMDM4b21lc1Q0eFEKQUFBRUFDV2FLbjBONzdLb1A1Tk9idGVNS0dVTG13dnNkWjlGdW9IR2RqcDgxdy84bGNBRFlDWTRGaXMzNm1wUmtMSnlpZgpBaXNOZWlQV2xMVGZ5aVo2eFBqRkFBQUFCbkI1ZEdodmJnRUNBd1FGQmdjPQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K