apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-root-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: default
  source:
    path: argocd-apps
    repoURL: git@github.com:srisaikadiyam96/python.git
    targetRevision: main
    
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
