apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:srisaikadiyam96/python.git
    targetRevision: main
    path: deployments/prod
  destination: 
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
