apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-qa
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:srisaikadiyam96/python.git
    targetRevision: main
    path: deployments/qa
  destination: 
    server: https://kubernetes.default.svc
    namespace: qa

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    # automated:
    #   selfHeal: true
    #   prune: true
    #   allowEmpty: true
