apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythondemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythondemo
      env: dev
      tier: frontend
  template:
    metadata:
      labels:
        app: pythondemo
        env: dev
        tier: frontend
    spec:
      containers:
        - name: pythondemo
          image: gitopstesting.jfrog.io/gitops-docker/python-app:5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: argocd-cred
      nodeSelector:
        kubernetes.io/os: linux
